#打开所有访问断点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

#打开env端点
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: reactor-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.4.5.139:3306/reactor-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: uWXf87plmQGz8zMM
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
      validation-query-timeout: 2000
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
        url-pattern: /*
  mvc:
    hiddenmethod:
      filter:
        enabled: false
    throw-exception-if-no-handler-found: true
    servlet:
      multipart:
        max-file-size: 256MB
        max-request-size: 1024MB
    web:
      resources:
        add-mappings: false
  redis:
    database: 0 #索引（默认为0）
    password: AhspHJ2l0ychcves  #连接密码（默认空）
    timeout: 5000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    cluster:
      nodes: 10.4.5.139:47001,10.4.5.139:47002,10.4.5.139:47003,10.4.5.104:47004,10.4.5.104:47005,10.4.5.104:47006
      max-redirects: 3

#mybatis-plus配置
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    #sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      insert-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
      select-strategy: not_null
      table-underline: true
      update-strategy: not_null
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.reactor.**.entity

