#打开所有访问断点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

#打开env端点
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: reactor-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: rootroot

  mvc:
    hiddenmethod:
      filter:
        enabled: false
    throw-exception-if-no-handler-found: true
    servlet:
      multipart:
        max-file-size: 256MB
        max-request-size: 1024MB
    web:
      resources:
        add-mappings: false
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1
    password: 123456  #连接密码（默认空）
    timeout: 5000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      rocketmq:
        binder:
          # 配置rocketmq的nameserver地址
          name-server: 127.0.0.1:9876
          # 不加, 会报错：Property 'group' is required - producerGroup
          group: rocketmq-group
        bindings:
          topic-consumer2: # 与 spring.cloud.stream.bindings.topic-consumer2对应上
            consumer:
              subscription: myTag||look # 基于 Tag 订阅，多个 Tag 使用 || 分隔，默认为空
      # 定义name为output的binding
      bindings:
        topic-producer:
          destination: test-topic
          content-type: application/json
          group: test-topic-producer
        # 定义name为input的binding
        topic-consumer1:
          destination: test-topic
          content-type: application/json
          group: test-group-comsumer1
        topic-consumer2:
          destination: test-topic
          content-type: application/json
          group: test-group-comsumer2

logging:
  level:
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.alibaba.cloud.stream.binder.rocketmq: info