#打开所有访问断点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

#打开env端点
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: reactor-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: rootroot

  mvc:
    hiddenmethod:
      filter:
        enabled: false
    throw-exception-if-no-handler-found: true
    servlet:
      multipart:
        max-file-size: 256MB
        max-request-size: 1024MB
    web:
      resources:
        add-mappings: false
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1
    password: 123456  #连接密码（默认空）
    timeout: 5000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
  main:
    allow-bean-definition-overriding: true
#    cluster:
#      nodes: 10.4.5.139:47001,10.4.5.139:47002,10.4.5.139:47003,10.4.5.104:47004,10.4.5.104:47005,10.4.5.104:47006
#      max-redirects: 3


logging:
  level:
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
